dist: trusty
sudo: false
language: minimal
before_install: true
install: true
before_script: true
script: true
notifications:
    webhooks:
        urls:
            - secure: Z5La0/nAYSt1/7B1lYAJQTmOJcdM8jp/6cjC6L/fU1dD0hMW03w0/r5ot4F9dKGOyQLq8VeVvQaFcJ85m6lUjjC0aFvjj7fKYBdSTuXwwlTe2LxTd/lPktnx3IT+w+pY4RFUEjldn1E6wW2scMkj5ktgftnnRK97cGtOwtc7cY42lSxl4iyIiUDIbIiNfUGJeHdLiiaj06oFonqZnv6zL4Spxme1nyyia1wsuZOQ3SuYRu2hGg41POROtHWmxiUp1NaXS0/SgffY1P8A3SYp0w1BKf7KHlQH1vTJErvvA4iJS4sYMHQzuH7sKefEQv35yFxpLREOo4HxU7BstXTH4Lsw75SWLZKLBn2X9m952YVaoZT+liV4Bjh1OhU26VyRkA5wyeK/QvFqqgaUZ8SQ18euika3a04hJFXYNHglCLUraj2BeWkSRW+/o/NJfN4UceSDnEFJx6WMi6Q5W67vx4T8THcxAZmWvM7QeAkh8fAW+SkKiAH8F6mRcPSl5E02WlTwBkQcHUcnBuN54Y2n75vGxGfK1WRiywQq2hNRAb9NjspRFvOYmiE3ccQ0ZssL77CJs1usKP3EbO9vPvTGBBI0oh8gZpVl4fM7ceF9e0LbR3Ck6Fk3++PzG8cslseG/H42n/436U7tiRHZgjIo6atfBcGI7pGSfZAQ9Ozf0Co=
